name: Build
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # choosing to run a reduced set of LTS, current, and next, to balance coverage and execution time
        java: [8, 11, 15]
        # Temporarily removed 16-ea, as it started failing in the japicmp plugin phase.
        # Working (with japacmp): https://github.com/jhy/jsoup/runs/1556442000?check_suite_focus=true
        # Failing: https://github.com/jhy/jsoup/runs/1556669892?check_suite_focus=true
        # Issue raised: https://github.com/siom79/japicmp/issues/275
      fail-fast: false
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-java-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven Compile
        run: mvn -X compile -B --file pom.xml

      - name: Maven Verify
        run: mvn -X verify -B --file pom.xml
...
